services:
  web:
    build: .
    image: vue-udemy-music:latest
    volumes:
      - ./src/public:/usr/src/app/public
      - ./src/src:/usr/src/app/src
      - ./src/tests:/usr/src/app/tests
      - ./src/package.json:/usr/src/app/package.json
      - ./src/package-lock.json:/usr/src/app/package-lock.json
    ports:
      - 8000:8080
